name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Fitur Baru'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'refactor'
  - title: '📝 Dokumentasi'
    labels:
      - 'documentation'

change-template: '- $TITLE (#$NUMBER) oleh @$AUTHOR'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'chore'
      - 'dependencies'
      - 'documentation'
      - 'refactor'

template: |
  ## Perubahan di v$RESOLVED_VERSION

  $CHANGES

  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
